name: Lawrence Yoga Collective
description: Lawrence Yoga Collective is a donation-based yoga stdio in Lawrence, MAx 

# url: http://lawrenceyoga.com
url: http://localhost:4000

left_header: news
left_text: Add the latest news here

paginate: 10

permalink: pretty
pygments: true


