name: Lawrence Yoga Collective
description: Lawrence Yoga Collective is a donation-based yoga stdio in Lawrence, MAx 

# url: http://lawrenceyoga.com
url: http://localhost:4000

left_header: news
left_text: <p>Begunner's series has been postponed until the fall. Watch here for details.</p>

paginate: 10

permalink: pretty
pygments: true


